apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: gutofunny/api-k8s-produto:latest
        ports:
        - containerPort: 8080
        env:
          - name: MONGO_URI
            value: mongodb://mongouser:mongopwd@localhost:27017/admin
