apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produtos
spec:
  replicas: 10
  selector:
    matchLabels:
      app: api-produtos
  template:
    metadata:
      labels:
        app: api-produtos
    spec:
      containers:
      - name: api-produtos
        image: gutofunny/api-k8s-produto:latest
        ports:
        - containerPort: 8080
        env:
          - name: MONGO_URI
            value: mongodb://mongouser:mongopwd@localhost:27017/admin
